### PR TITLE
Background gradient issue resolved.

### PR DESCRIPTION
**Pull request by curator69**
Resolved the issue, where the background gradient was not covering the entire height of the viewport in the mobile device

### CODE REVIEW

**Comment by princid** [comment]
Can you please add some images so that I can verify it!

**Comment by curator69** [comment]
Screenshot (100)

**Comment by curator69** [comment]
hey, any update?

**Comment by curator69** [comment]
also let me know if any other changes need to be done.

**Comment by princid** [comment]
It is showing that this branch has some conflicts that must be resolved, so I'm not being able to merge your pull request.
image

**Comment by curator69** [comment]
so what should i do?

**Comment by princid** [comment]
Don't worry, I will merge your pull request after resolving this issue.

**Comment by curator69** [comment]
okay let me know once u r done, or i just pull the latest repo and then push it again.

**Pull request closed without merging**
